# Generated by Django 6.0 on 2025-12-25 15:47

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام نویسنده")),
                ("bio", models.TextField(verbose_name="بیوگرافی نویسنده")),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="authors/", verbose_name="تصویر پروفایل نویسنده"
                    ),
                ),
            ],
            options={
                "verbose_name": "نویسنده",
                "verbose_name_plural": "نویسندگان",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="اسلاگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان مقاله")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=350,
                        unique=True,
                        verbose_name="اسلاگ (آدرس URL)",
                    ),
                ),
                (
                    "content",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="محتوای مقاله"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        upload_to="articles/", verbose_name="تصویر اصلی مقاله"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="زمان تقریبی خواندن به دقیقه",
                        verbose_name="زمان خواندن",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="تگ\u200cها را با کاما جدا کنید، مثال: ورد, آفیس, ترفند, آموزش",
                        max_length=500,
                        verbose_name="تگ\u200cها",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.author",
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-created_at"],
            },
        ),
    ]
