# Generated by Django 6.0 on 2025-12-25 16:05

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان دوره")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=350, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "description",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="توضیحات دوره"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="courses/", verbose_name="تصویر دوره"),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                (
                    "duration",
                    models.CharField(
                        max_length=100, verbose_name="مدت زمان (مثلاً ۲۰ ساعت)"
                    ),
                ),
                (
                    "features",
                    models.TextField(verbose_name="ویژگی\u200cها (هر کدام در خط جدا)"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره آموزشی",
                "verbose_name_plural": "دوره\u200cهای آموزشی",
                "ordering": ["-start_date"],
            },
        ),
    ]
