# Generated by Django 6.0 on 2025-12-25 16:27

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="عنوان اطلاعیه"),
                ),
                (
                    "description",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="announcements/", verbose_name="تصویر"),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                (
                    "features",
                    models.TextField(verbose_name="ویژگی\u200cها (هر خط یکی)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "اطلاعیه دوره",
                "verbose_name_plural": "اطلاعیه\u200cهای دوره",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کاربر")),
                ("role", models.CharField(max_length=100, verbose_name="سمت یا دوره")),
                ("text", models.TextField(verbose_name="متن نظر")),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="testimonials/", verbose_name="تصویر پروفایل"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
            ],
            options={
                "verbose_name": "نظر کاربر",
                "verbose_name_plural": "نظرات کاربران",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="آیکون (مثلاً 📐 برای اتوکد)"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=5, verbose_name="زمان خواندن (دقیقه)"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="تگ\u200cها (با کاما جدا کنید)"
            ),
        ),
    ]
