# Generated by Django 6.0 on 2025-12-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_announcement_testimonial_category_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=350, unique=True, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="تگ\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="آیکون (مثلاً 📐)"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.CharField(max_length=100, verbose_name="مدت زمان"),
        ),
        migrations.AlterField(
            model_name="course",
            name="features",
            field=models.TextField(verbose_name="ویژگی\u200cها (هر خط یکی)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="avatar",
            field=models.ImageField(upload_to="testimonials/", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=models.CharField(max_length=100, verbose_name="سمت/دوره"),
        ),
    ]
