# Generated by Django 6.0 on 2025-12-25 17:15

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_alter_article_slug_alter_article_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="درباره ما", max_length=300, verbose_name="عنوان صفحه"
                    ),
                ),
                (
                    "text",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="متن درباره ما"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="تصویر درباره ما",
                    ),
                ),
            ],
            options={
                "verbose_name": "محتوای درباره ما",
                "verbose_name_plural": "محتواهای درباره ما",
            },
        ),
        migrations.CreateModel(
            name="AboutStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=25, verbose_name="سال\u200cهای تجربه"
                    ),
                ),
                (
                    "graduates",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="دانش\u200cآموزان فارغ\u200cالتحصیل"
                    ),
                ),
                (
                    "courses",
                    models.PositiveIntegerField(
                        default=50, verbose_name="دوره\u200cهای آموزشی"
                    ),
                ),
                (
                    "teachers",
                    models.PositiveIntegerField(default=30, verbose_name="اساتید مجرب"),
                ),
            ],
            options={
                "verbose_name": "آمار درباره ما",
                "verbose_name_plural": "آمارهای درباره ما",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
    ]
